CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    full_name TEXT NOT NULL,
    title TEXT NOT NULL,
    bio TEXT NOT NULL,
    theme_color TEXT NOT NULL,
    github_url TEXT,
    linkedin_url TEXT,
    email_address TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);