CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    full_name TEXT NOT NULL,
    title TEXT,
    bio TEXT,
    profile_picture TEXT,
    theme_color TEXT DEFAULT 'black',
    banner_image TEXT DEFAULT 'mountains',
    github_url TEXT,
    linkedin_url TEXT,
    email_address TEXT,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);